version: "3"

services:
  web:
    build: .
    environment:
      - ENVIRONMENT=production
      - DATABASE_URI=mongodb+srv://victorjmanrique:dkNFytNImc2EdQAd@financii.6cysdzs.mongodb.net/?retryWrites=true&w=majority
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
